# ============================================================
# outputs.tf
# ------------------------------------------------------------
# This file handles the "Automation Bridge" between AWS and Ansible.
# 1. It creates the Application Load Balancer (ALB).
# 2. It creates the Ansible inventory.ini file automatically.
# 3. It prints SSH shortcuts to your terminal.
# ============================================================

# ===========================================================
# 1. APPLICATION LOAD BALANCER (ALB) SETUP
# ===========================================================

resource "aws_lb" "main" {
  name               = "${var.project_name}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = [aws_subnet.public_1.id, aws_subnet.public_2.id]
  enable_deletion_protection = false

  tags = {
    Name        = "${var.project_name}-alb"
    Project     = var.project_name
  }
}

# Target Group: Jenkins (Port 8080)
resource "aws_lb_target_group" "jenkins" {
  name     = "${var.project_name}-jenkins-tg"
  port     = 8080
  protocol = "HTTP"
  vpc_id   = aws_vpc.main.id

  health_check {
    path                = "/login"
    port                = "traffic-port"
    healthy_threshold   = 2
    unhealthy_threshold = 3
    matcher             = "200,302"
  }
}

# Target Group: Grafana (Port 3000)
resource "aws_lb_target_group" "grafana" {
  name     = "${var.project_name}-grafana-tg"
  port     = 3000
  protocol = "HTTP"
  vpc_id   = aws_vpc.main.id

  health_check {
    path                = "/api/health"
    matcher             = "200"
  }
}

# Attachments
resource "aws_lb_target_group_attachment" "jenkins" {
  target_group_arn = aws_lb_target_group.jenkins.arn
  target_id        = aws_instance.build_server.id
  port             = 8080
}

resource "aws_lb_target_group_attachment" "grafana" {
  target_group_arn = aws_lb_target_group.grafana.arn
  target_id        = aws_instance.monitoring_server.id
  port             = 3000
}

# Listener
resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.main.arn
  port              = "80"
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.jenkins.arn
  }
}

# Rule for Grafana routing
resource "aws_lb_listener_rule" "grafana" {
  listener_arn = aws_lb_listener.http.arn
  priority     = 100
  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.grafana.arn
  }
  condition {
    path_pattern {
      values = ["/grafana*"]
    }
  }
}

# ===========================================================
# 2. AUTO-GENERATE ANSIBLE INVENTORY
# ===========================================================

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"

  content = <<-EOT
# AUTO-GENERATED BY TERRAFORM
[build_servers]
build_server ansible_host=${aws_instance.build_server.public_ip}

[monitoring_servers]
monitoring_server ansible_host=${aws_instance.monitoring_server.public_ip}

[k8s_master]
k8s_master ansible_host=${aws_instance.k8s_master.public_ip}

[k8s_workers]
k8s_worker1 ansible_host=${aws_instance.k8s_worker1.public_ip}
k8s_worker2 ansible_host=${aws_instance.k8s_worker2.public_ip}

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${var.ssh_private_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s_nodes:children]
k8s_master
k8s_workers

[all_servers:children]
build_servers
monitoring_servers
k8s_nodes
EOT
}

# ===========================================================
# 3. TERMINAL OUTPUTS
# ===========================================================

output "alb_dns_name" {
  value = aws_lb.main.dns_name
}

output "urls" {
  value = {
    jenkins = "http://${aws_lb.main.dns_name}"
    grafana = "http://${aws_lb.main.dns_name}/grafana"
  }
}

output "ssh_shortcuts" {
  value = {
    build      = "ssh -i ${var.ssh_private_key_path} ubuntu@${aws_instance.build_server.public_ip}"
    monitoring = "ssh -i ${var.ssh_private_key_path} ubuntu@${aws_instance.monitoring_server.public_ip}"
    master     = "ssh -i ${var.ssh_private_key_path} ubuntu@${aws_instance.k8s_master.public_ip}"
    worker1    = "ssh -i ${var.ssh_private_key_path} ubuntu@${aws_instance.k8s_worker1.public_ip}"
    worker2    = "ssh -i ${var.ssh_private_key_path} ubuntu@${aws_instance.k8s_worker2.public_ip}"
  }
}