# ==============================================================================
# cleanup.yml - Stops containers & removes MicroK8s safely
# ==============================================================================
---
- name: Cleanup Services
  hosts: all
  become: yes
  tasks:
    - name: Stop & Remove all Docker containers
      docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
      loop: [jenkins, grafana, prometheus]

    - name: Remove Docker volumes
      docker_volume:
        name: "{{ item }}"
        state: absent
      loop: [jenkins_home, prometheus_data]

    - name: Remove MicroK8s
      command: snap remove microk8s --purge
      failed_when: false